
-- ATUALIZA OS VALORES DA NOTA FISCAL 


-- OBS: VIEW CRIADA PARA OBTERMOS A SOMA TOTAL DOS VALORES DA NOTA FISCAL, 
-- AGRUPANDO AS NOTAS QUE FOREM IGUAIS E SOMANDO SEUS VALORES.

CREATE VIEW V_NOTA_FISCAL 
 AS
SELECT ID_NOTA_FISCAL, SUM(TOTAL) AS SOMA
FROM ITEM_NOTA
GROUP BY ID_NOTA_FISCAL;
GO

SELECT * FROM V_NOTA_FISCAL;
GO


-- OBS: VIEW CRIADA PARA MOSTRAR QUE COLUNA TOTAL NOTA ESTÁ NULA, 
-- E A COLUNA SOMA, POSSUI OS VALORES TOTAIS DAS NOTAS FISCAIS

CREATE VIEW V_CARGA_NF
 AS
SELECT N.IDNOTA, N.TOTAL AS "TOTAL NOTA", V.SOMA
FROM NOTA_FISCAL N
INNER JOIN V_NOTA_FISCAL V
ON N.IDNOTA = V.ID_NOTA_FISCAL;
GO

SELECT * FROM V_CARGA_NF;
GO


--OBS: UPDATE FEITO, PARA PEGAR OS VALORES DA COLUNA SOMA 
-- E COLOCAR NA COLUNA TOTAL NOTA QUE ANTES ESTAVA NULA 

UPDATE V_CARGA_NF
SET [TOTAL NOTA] = SOMA;
GO


-- OS TOTAIS DA NOTA AGORA ESTÃO NA COLUNA CERTA
SELECT * FROM NOTA_FISCAL;
GO


-- VIEW DE RELATORIO OLTP

 CREATE VIEW V_RELATORIO_OLTP
 AS
 SELECT C.NOME, C.SOBRENOME, C.SEXO, N.DATA, N.IDNOTA, P.PRODUTO, N.TOTAL
 FROM CLIENTE C
 INNER JOIN NOTA_FISCAL N
 ON C.IDCLIENTE = N.ID_CLIENTE
 INNER JOIN ITEM_NOTA  I
 ON N.IDNOTA = I.ID_NOTA_FISCAL
 INNER JOIN PRODUTO P
 ON P.IDPRODUTO = I.ID_PRODUTO;
 GO

 SELECT * FROM V_RELATORIO_OLTP
 ORDER BY 5;
 GO


 
