
-- CRIANDO UMA QUERY PARA RELATÓRIO DE REGIÃO

	SELECT REGIAO, ANO,
	SUM(F.LUCROTOTAL) AS LUCRO,
	SUM(F.QUANTIDADE) AS QTD,
	SUM(F.TOTALITEM) AS TOTAL,
	SUM(F.CUSTOTOTAL) AS CUSTO
	FROM DIM_CLIENTE
	INNER JOIN FATO F
	ON IDSK = F.IDCLIENTE
	INNER JOIN DIM_TEMPO T
	ON T.IDSK = IDTEMPO 
	GROUP BY REGIAO, ANO
	ORDER BY 1,2