
USE COMERCIO_DW;
GO

-- RESOLVENDO AS QUESTÕES DE NEGOCIO


-- QUEM SÃO MEUS MELHORES CLIENTES

SELECT TOP 200
       C.NOME,
	   C.EMAIL,
	   C.CIDADE,
	   C.ESTADO,
	   C.REGIAO,
	  SUM(F.TOTALITEM) AS TOTAL_VENDA
FROM FATO F
INNER JOIN DIM_CLIENTE C
ON F.IDCLIENTE = C.IDSK
GROUP BY C.NOME, C.EMAIL,C.CIDADE, C.ESTADO, C.REGIAO
ORDER BY 6 DESC;
GO


-- QUEM SÃO OS MELHORES VENDEDORES

SELECT TOP 10
		V.NOME,
		T.ANO,
		SUM(F.TOTALITEM) AS TOTAL_VENDA
FROM FATO F
INNER JOIN DIM_VENDEDOR V
ON F.IDVENDEDOR = V.IDSK
INNER JOIN DIM_TEMPO T
ON F.IDTEMPO = T.IDSK
GROUP BY V.NOME, T.ANO
ORDER BY 3 DESC;
GO


-- QUAL CATEGORIA VENDE MAIS

SELECT
		C.NOME,
		SUM(F.TOTALITEM) AS TOTAL_VENDA
FROM FATO F
INNER JOIN DIM_PRODUTO P
ON F.IDPRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY 2 DESC;
GO


-- QUAL A MINHA RELAÇÃO COM OS FORNECEDORES 

SELECT
		FO.NOME,
		SUM(F.TOTALITEM) AS TOTAL_VENDA,
		SUM(F.CUSTOTOTAL) AS TOTAL_CUSTO,
		SUM(F.LUCROTOTAL) AS TOTAL_LUCRO
FROM FATO F
INNER JOIN DIM_FORNECEDOR FO
ON F.IDFORNECEDOR = FO.IDSK
GROUP BY FO.NOME
ORDER BY 4;
GO


-- QUAL MEU MELHOR PRODUTO 

SELECT TOP 1
		P.NOME,
		SUM(F.TOTALITEM) AS TOTAL_VENDA
FROM FATO F
INNER JOIN DIM_PRODUTO P
ON F.IDPRODUTO = P.IDSK
GROUP BY P.NOME
ORDER BY 2 DESC;
GO


-- QUAL MEU PIOR PRODUTO

SELECT TOP 1
		P.NOME,
		SUM(F.TOTALITEM) AS TOTAL_VENDA
FROM FATO F
INNER JOIN DIM_PRODUTO P
ON F.IDPRODUTO = P.IDSK
GROUP BY P.NOME
ORDER BY 2 ASC;
GO


-- EM QUAL REGIAO VENDO MAIS

SELECT	
		C.REGIAO,
		SUM(F.TOTALITEM) AS TOTAL_VENDA
FROM FATO F
INNER JOIN DIM_CLIENTE C
ON F.IDCLIENTE = C.IDSK
GROUP BY C.REGIAO
ORDER BY 2 DESC;
GO


-- EM QUE EPOCA DO ANO EU TENHO MAIS GASTO -> POR ESTAÇÃO 
SELECT 
		T.ESTACAOANO AS ESTAÇÃO_DO_ANO,
		SUM(F.CUSTOTOTAL) AS TOTAL_GASTO
FROM FATO F
INNER JOIN DIM_TEMPO T
ON F.IDTEMPO = T.IDSK
GROUP BY T.ESTACAOANO
ORDER BY 2 DESC;
GO

-- EM QUE EPOCA DO ANO EU TENHO MAIS GASTO -> POR MÊS
SELECT 
	    T.MES AS MÊS,
		SUM(F.CUSTOTOTAL) AS TOTAL_GASTO
FROM FATO F
INNER JOIN DIM_TEMPO T
ON F.IDTEMPO = T.IDSK
GROUP BY T.MES
ORDER BY 2 DESC;
GO


-- EM QUE EPOCA LUCRO MAIS -> POR ESTAÇÃO 
SELECT 
		T.ESTACAOANO AS ESTAÇÃO_DO_ANO,
		SUM(F.LUCROTOTAL) AS TOTAL_LUCRO
FROM FATO F
INNER JOIN DIM_TEMPO T
ON F.IDTEMPO = T.IDSK
GROUP BY T.ESTACAOANO
ORDER BY 2 DESC;
GO

-- EM QUE EPOCA LUCRO MAIS -> POR MÊS
SELECT 
	    T.MES AS MÊS,
		SUM(F.LUCROTOTAL) AS TOTAL_LUCRO
FROM FATO F
INNER JOIN DIM_TEMPO T
ON F.IDTEMPO = T.IDSK
GROUP BY T.MES
ORDER BY 2 DESC;
GO









SELECT TOP 4
	   P.NOME,
	   SUM(F.TOTALITEM) AS TOTAL_ITEM
FROM FATO F
INNER JOIN DIM_PRODUTO P
ON F.IDPRODUTO = P.IDPRODUTO
GROUP BY P.NOME
ORDER BY 2 ASC;
GO
